server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #表示是否将自已注册进EurekaServer默认为true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓，集群必需设置为true,从能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
